[theme]
primaryColor = "#4169E1"  # Royal Blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false 